name: helm-eks-action

env:
  TAG: ${{ secrets.DOCKERHUB_USERNAME }}/helm-deploy:v1.${{ github.run_id }}
  LATEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/helm-deploy:latest

on:
  workflow_dispatch

jobs:

  buildAndPush:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.TAG }},${{ env.LATEST_TAG }}